//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sixeyed.CarValet.Api.ServiceAgents.Wcf.Content {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContentItem", Namespace="http://schemas.datacontract.org/2004/07/Sixeyed.CarValet.Services.Entities")]
    [System.SerializableAttribute()]
    public partial class ContentItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsHtmlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Index {
            get {
                return this.IndexField;
            }
            set {
                if ((this.IndexField.Equals(value) != true)) {
                    this.IndexField = value;
                    this.RaisePropertyChanged("Index");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsHtml {
            get {
                return this.IsHtmlField;
            }
            set {
                if ((this.IsHtmlField.Equals(value) != true)) {
                    this.IsHtmlField = value;
                    this.RaisePropertyChanged("IsHtml");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceAgents.Wcf.Content.ContentService")]
    public interface ContentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ContentService/GetItems", ReplyAction="http://tempuri.org/ContentService/GetItemsResponse")]
        Sixeyed.CarValet.Api.ServiceAgents.Wcf.Content.ContentItem[] GetItems(string contentCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ContentService/GetItems", ReplyAction="http://tempuri.org/ContentService/GetItemsResponse")]
        System.Threading.Tasks.Task<Sixeyed.CarValet.Api.ServiceAgents.Wcf.Content.ContentItem[]> GetItemsAsync(string contentCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ContentServiceChannel : Sixeyed.CarValet.Api.ServiceAgents.Wcf.Content.ContentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContentServiceClient : System.ServiceModel.ClientBase<Sixeyed.CarValet.Api.ServiceAgents.Wcf.Content.ContentService>, Sixeyed.CarValet.Api.ServiceAgents.Wcf.Content.ContentService {
        
        public ContentServiceClient() {
        }
        
        public ContentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Sixeyed.CarValet.Api.ServiceAgents.Wcf.Content.ContentItem[] GetItems(string contentCode) {
            return base.Channel.GetItems(contentCode);
        }
        
        public System.Threading.Tasks.Task<Sixeyed.CarValet.Api.ServiceAgents.Wcf.Content.ContentItem[]> GetItemsAsync(string contentCode) {
            return base.Channel.GetItemsAsync(contentCode);
        }
    }
}
