//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace _09_14_02
{
    #region 內容
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    public partial class XINEntities : ObjectContext
    {
        #region 建構函式
    
        /// <summary>
        /// 使用在應用程式組態檔的 'XINEntities' 區段中找到的連接字串，初始化新的 XINEntities 物件。
        /// </summary>
        public XINEntities() : base("name=XINEntities", "XINEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 XINEntities 物件。
        /// </summary>
        public XINEntities(string connectionString) : base(connectionString, "XINEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 XINEntities 物件。
        /// </summary>
        public XINEntities(EntityConnection connection) : base(connection, "XINEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 部分方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<Programs> Programs
        {
            get
            {
                if ((_Programs == null))
                {
                    _Programs = base.CreateObjectSet<Programs>("Programs");
                }
                return _Programs;
            }
        }
        private ObjectSet<Programs> _Programs;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 將新物件加入 Programs EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddToPrograms(Programs programs)
        {
            base.AddObject("Programs", programs);
        }

        #endregion

    }

    #endregion

    #region 實體
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XINModel", Name="Programs")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Programs : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 Programs 物件。
        /// </summary>
        /// <param name="programID">ProgramID 屬性的初始值。</param>
        /// <param name="programName">ProgramName 屬性的初始值。</param>
        public static Programs CreatePrograms(global::System.String programID, global::System.String programName)
        {
            Programs programs = new Programs();
            programs.ProgramID = programID;
            programs.ProgramName = programName;
            return programs;
        }

        #endregion

        #region 簡單屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProgramID
        {
            get
            {
                return _ProgramID;
            }
            set
            {
                if (_ProgramID != value)
                {
                    OnProgramIDChanging(value);
                    ReportPropertyChanging("ProgramID");
                    _ProgramID = StructuralObject.SetValidValue(value, false, "ProgramID");
                    ReportPropertyChanged("ProgramID");
                    OnProgramIDChanged();
                }
            }
        }
        private global::System.String _ProgramID;
        partial void OnProgramIDChanging(global::System.String value);
        partial void OnProgramIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProgramName
        {
            get
            {
                return _ProgramName;
            }
            set
            {
                if (_ProgramName != value)
                {
                    OnProgramNameChanging(value);
                    ReportPropertyChanging("ProgramName");
                    _ProgramName = StructuralObject.SetValidValue(value, false, "ProgramName");
                    ReportPropertyChanged("ProgramName");
                    OnProgramNameChanged();
                }
            }
        }
        private global::System.String _ProgramName;
        partial void OnProgramNameChanging(global::System.String value);
        partial void OnProgramNameChanged();

        #endregion

    }

    #endregion

}
