//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sixeyed.CarValet.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PricingFactorType
    {
        public PricingFactorType()
        {
            this.PricingFactors = new HashSet<PricingFactor>();
        }
    
        public string PricingFactorTypeCode { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<PricingFactor> PricingFactors { get; set; }
    }
}
