//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("moviereviewsModel", "fk_reviews_movies", "movies", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Cslinq.Movie), "reviews", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Cslinq.Review), true)]

#endregion

namespace Cslinq
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MovieDB : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MovieDB object using the connection string found in the 'MovieDB' section of the application configuration file.
        /// </summary>
        public MovieDB() : base("name=MovieDB", "MovieDB")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MovieDB object.
        /// </summary>
        public MovieDB(string connectionString) : base(connectionString, "MovieDB")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MovieDB object.
        /// </summary>
        public MovieDB(EntityConnection connection) : base(connection, "MovieDB")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Movie> Movies
        {
            get
            {
                if ((_Movies == null))
                {
                    _Movies = base.CreateObjectSet<Movie>("Movies");
                }
                return _Movies;
            }
        }
        private ObjectSet<Movie> _Movies;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Review> Reviews
        {
            get
            {
                if ((_Reviews == null))
                {
                    _Reviews = base.CreateObjectSet<Review>("Reviews");
                }
                return _Reviews;
            }
        }
        private ObjectSet<Review> _Reviews;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Movies EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMovies(Movie movie)
        {
            base.AddObject("Movies", movie);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Reviews EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReviews(Review review)
        {
            base.AddObject("Reviews", review);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="moviereviewsModel", Name="Movie")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Movie : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Movie object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="releaseDate">Initial value of the ReleaseDate property.</param>
        public static Movie CreateMovie(global::System.Int32 id, global::System.String title, global::System.DateTime releaseDate)
        {
            Movie movie = new Movie();
            movie.ID = id;
            movie.Title = title;
            movie.ReleaseDate = releaseDate;
            return movie;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ReleaseDate
        {
            get
            {
                return _ReleaseDate;
            }
            set
            {
                OnReleaseDateChanging(value);
                ReportPropertyChanging("ReleaseDate");
                _ReleaseDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReleaseDate");
                OnReleaseDateChanged();
            }
        }
        private global::System.DateTime _ReleaseDate;
        partial void OnReleaseDateChanging(global::System.DateTime value);
        partial void OnReleaseDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("moviereviewsModel", "fk_reviews_movies", "reviews")]
        public EntityCollection<Review> Reviews
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Review>("moviereviewsModel.fk_reviews_movies", "reviews");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Review>("moviereviewsModel.fk_reviews_movies", "reviews", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="moviereviewsModel", Name="Review")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Review : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Review object.
        /// </summary>
        /// <param name="review_id">Initial value of the review_id property.</param>
        /// <param name="movie_id">Initial value of the movie_id property.</param>
        /// <param name="summary">Initial value of the summary property.</param>
        /// <param name="rating">Initial value of the rating property.</param>
        /// <param name="review1">Initial value of the review1 property.</param>
        public static Review CreateReview(global::System.Int32 review_id, global::System.Int32 movie_id, global::System.String summary, global::System.Int32 rating, global::System.String review1)
        {
            Review review = new Review();
            review.review_id = review_id;
            review.movie_id = movie_id;
            review.summary = summary;
            review.rating = rating;
            review.review1 = review1;
            return review;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 review_id
        {
            get
            {
                return _review_id;
            }
            set
            {
                if (_review_id != value)
                {
                    Onreview_idChanging(value);
                    ReportPropertyChanging("review_id");
                    _review_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("review_id");
                    Onreview_idChanged();
                }
            }
        }
        private global::System.Int32 _review_id;
        partial void Onreview_idChanging(global::System.Int32 value);
        partial void Onreview_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 movie_id
        {
            get
            {
                return _movie_id;
            }
            set
            {
                Onmovie_idChanging(value);
                ReportPropertyChanging("movie_id");
                _movie_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("movie_id");
                Onmovie_idChanged();
            }
        }
        private global::System.Int32 _movie_id;
        partial void Onmovie_idChanging(global::System.Int32 value);
        partial void Onmovie_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String summary
        {
            get
            {
                return _summary;
            }
            set
            {
                OnsummaryChanging(value);
                ReportPropertyChanging("summary");
                _summary = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("summary");
                OnsummaryChanged();
            }
        }
        private global::System.String _summary;
        partial void OnsummaryChanging(global::System.String value);
        partial void OnsummaryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 rating
        {
            get
            {
                return _rating;
            }
            set
            {
                OnratingChanging(value);
                ReportPropertyChanging("rating");
                _rating = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rating");
                OnratingChanged();
            }
        }
        private global::System.Int32 _rating;
        partial void OnratingChanging(global::System.Int32 value);
        partial void OnratingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String review1
        {
            get
            {
                return _review1;
            }
            set
            {
                Onreview1Changing(value);
                ReportPropertyChanging("review1");
                _review1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("review1");
                Onreview1Changed();
            }
        }
        private global::System.String _review1;
        partial void Onreview1Changing(global::System.String value);
        partial void Onreview1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String reviewer
        {
            get
            {
                return _reviewer;
            }
            set
            {
                OnreviewerChanging(value);
                ReportPropertyChanging("reviewer");
                _reviewer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("reviewer");
                OnreviewerChanged();
            }
        }
        private global::System.String _reviewer;
        partial void OnreviewerChanging(global::System.String value);
        partial void OnreviewerChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("moviereviewsModel", "fk_reviews_movies", "movies")]
        public Movie movy
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Movie>("moviereviewsModel.fk_reviews_movies", "movies").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Movie>("moviereviewsModel.fk_reviews_movies", "movies").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Movie> movyReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Movie>("moviereviewsModel.fk_reviews_movies", "movies");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Movie>("moviereviewsModel.fk_reviews_movies", "movies", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
