//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sixeyed.Disposable.DomainConsoleApp.ServiceAgents.WordCount {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceAgents.WordCount.WordCountService")]
    public interface WordCountService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WordCountService/GetWordCount", ReplyAction="http://tempuri.org/WordCountService/GetWordCountResponse")]
        int GetWordCount(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WordCountService/GetWordCount", ReplyAction="http://tempuri.org/WordCountService/GetWordCountResponse")]
        System.Threading.Tasks.Task<int> GetWordCountAsync(string input);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WordCountServiceChannel : Sixeyed.Disposable.DomainConsoleApp.ServiceAgents.WordCount.WordCountService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WordCountServiceClient : System.ServiceModel.ClientBase<Sixeyed.Disposable.DomainConsoleApp.ServiceAgents.WordCount.WordCountService>, Sixeyed.Disposable.DomainConsoleApp.ServiceAgents.WordCount.WordCountService {
        
        public WordCountServiceClient() {
        }
        
        public WordCountServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WordCountServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordCountServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordCountServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetWordCount(string input) {
            return base.Channel.GetWordCount(input);
        }
        
        public System.Threading.Tasks.Task<int> GetWordCountAsync(string input) {
            return base.Channel.GetWordCountAsync(input);
        }
    }
}
