//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sixeyed.CarValet.Api.ServiceAgents.Wcf.Vehicle {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vehicle", Namespace="http://schemas.datacontract.org/2004/07/Sixeyed.CarValet.Services.Entities")]
    [System.SerializableAttribute()]
    public partial class Vehicle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MakeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ProducedFromUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ProducedToUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VehicleIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Make {
            get {
                return this.MakeField;
            }
            set {
                if ((object.ReferenceEquals(this.MakeField, value) != true)) {
                    this.MakeField = value;
                    this.RaisePropertyChanged("Make");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ProducedFromUtc {
            get {
                return this.ProducedFromUtcField;
            }
            set {
                if ((this.ProducedFromUtcField.Equals(value) != true)) {
                    this.ProducedFromUtcField = value;
                    this.RaisePropertyChanged("ProducedFromUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ProducedToUtc {
            get {
                return this.ProducedToUtcField;
            }
            set {
                if ((this.ProducedToUtcField.Equals(value) != true)) {
                    this.ProducedToUtcField = value;
                    this.RaisePropertyChanged("ProducedToUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VehicleId {
            get {
                return this.VehicleIdField;
            }
            set {
                if ((this.VehicleIdField.Equals(value) != true)) {
                    this.VehicleIdField = value;
                    this.RaisePropertyChanged("VehicleId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceAgents.Wcf.Vehicle.VehicleService")]
    public interface VehicleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VehicleService/SearchMakes", ReplyAction="http://tempuri.org/VehicleService/SearchMakesResponse")]
        string[] SearchMakes(string startsWith);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VehicleService/SearchMakes", ReplyAction="http://tempuri.org/VehicleService/SearchMakesResponse")]
        System.Threading.Tasks.Task<string[]> SearchMakesAsync(string startsWith);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VehicleService/SearchModels", ReplyAction="http://tempuri.org/VehicleService/SearchModelsResponse")]
        string[] SearchModels(string makeName, string startsWith);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VehicleService/SearchModels", ReplyAction="http://tempuri.org/VehicleService/SearchModelsResponse")]
        System.Threading.Tasks.Task<string[]> SearchModelsAsync(string makeName, string startsWith);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VehicleService/GetByMakeAndModel", ReplyAction="http://tempuri.org/VehicleService/GetByMakeAndModelResponse")]
        Sixeyed.CarValet.Api.ServiceAgents.Wcf.Vehicle.Vehicle[] GetByMakeAndModel(string makeName, string modelName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VehicleService/GetByMakeAndModel", ReplyAction="http://tempuri.org/VehicleService/GetByMakeAndModelResponse")]
        System.Threading.Tasks.Task<Sixeyed.CarValet.Api.ServiceAgents.Wcf.Vehicle.Vehicle[]> GetByMakeAndModelAsync(string makeName, string modelName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VehicleService/GetById", ReplyAction="http://tempuri.org/VehicleService/GetByIdResponse")]
        Sixeyed.CarValet.Api.ServiceAgents.Wcf.Vehicle.Vehicle GetById(int vehicleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VehicleService/GetById", ReplyAction="http://tempuri.org/VehicleService/GetByIdResponse")]
        System.Threading.Tasks.Task<Sixeyed.CarValet.Api.ServiceAgents.Wcf.Vehicle.Vehicle> GetByIdAsync(int vehicleId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VehicleServiceChannel : Sixeyed.CarValet.Api.ServiceAgents.Wcf.Vehicle.VehicleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VehicleServiceClient : System.ServiceModel.ClientBase<Sixeyed.CarValet.Api.ServiceAgents.Wcf.Vehicle.VehicleService>, Sixeyed.CarValet.Api.ServiceAgents.Wcf.Vehicle.VehicleService {
        
        public VehicleServiceClient() {
        }
        
        public VehicleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VehicleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehicleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehicleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] SearchMakes(string startsWith) {
            return base.Channel.SearchMakes(startsWith);
        }
        
        public System.Threading.Tasks.Task<string[]> SearchMakesAsync(string startsWith) {
            return base.Channel.SearchMakesAsync(startsWith);
        }
        
        public string[] SearchModels(string makeName, string startsWith) {
            return base.Channel.SearchModels(makeName, startsWith);
        }
        
        public System.Threading.Tasks.Task<string[]> SearchModelsAsync(string makeName, string startsWith) {
            return base.Channel.SearchModelsAsync(makeName, startsWith);
        }
        
        public Sixeyed.CarValet.Api.ServiceAgents.Wcf.Vehicle.Vehicle[] GetByMakeAndModel(string makeName, string modelName) {
            return base.Channel.GetByMakeAndModel(makeName, modelName);
        }
        
        public System.Threading.Tasks.Task<Sixeyed.CarValet.Api.ServiceAgents.Wcf.Vehicle.Vehicle[]> GetByMakeAndModelAsync(string makeName, string modelName) {
            return base.Channel.GetByMakeAndModelAsync(makeName, modelName);
        }
        
        public Sixeyed.CarValet.Api.ServiceAgents.Wcf.Vehicle.Vehicle GetById(int vehicleId) {
            return base.Channel.GetById(vehicleId);
        }
        
        public System.Threading.Tasks.Task<Sixeyed.CarValet.Api.ServiceAgents.Wcf.Vehicle.Vehicle> GetByIdAsync(int vehicleId) {
            return base.Channel.GetByIdAsync(vehicleId);
        }
    }
}
